### ISSUE TITLE
Track and notify reasons for container restarts

### ISSUE THREAD

**Issue by LawiK974** [LawiK974/kube-notify#38]
Since core event doesn't include container restarts, it could be a nice addition to iterate over all pods every x minutes to search for `spec.containers[*].lastState.terminated.reason` and notify if this field exists and `lastState.terminated.startedAt > STARTUP_TIME` 

Suggestion for field to send :

```yaml
- namespace
- pod/container
- reason
- exitCode
- finishedAt (if this field exists state might have been changed)
- startedAt
- message (if exists)
```

The title message could be for instance (if `restartPolicy: Always, OnFailure` : 

`OOMKilled(127): my-app/wordpress restarted`

or if `restartPolicy: Never` :

`Error(137) : my-app/postgresql terminated`

**Comment by LawiK974** [comment]
#41 merged just have to add in `config.yaml` : 
```yaml
events:
  coreApiEvents:
    addPodTerminationErrors: true  # parse all pod statuses to detect restart reasons as Errors and append to other events
```
